Fix missing dependency output and job events
Here is a generated commit message:


      Treat "no such path" output from jj file show as a missing file so todo
      readiness checks tolerate repos without dependencies.jsonl, and add
      coverage for file-not-found parsing. Ensure ii job do always shuts down
      its event printer on completion to avoid deadlocks when the runner
      leaves the event stream open.

This commit is a step towards implementing this todo:


      ID: 4jdr5sqj

      Title: crash bug

      Type: bug

      Priority: 0 (critical)

      Description:

          Error: read dependencies: jj file show: exit status 1: Error: No
          such path: dependencies.jsonl

          Usage: ii todo ready [flags]

          Flags: -h, --help help for ready --json Output as JSON --limit int
          Maximum
          number of todos to show (default 20)

          |
          | | fixing fatal error: all goroutines are asleep - deadlock!

          goroutine 1 [chan receive]: main.runJobDo(0x105242880,
          {0x14000708110, 0x1, 0x104839bea?})
          /Users/ajm/Work/incrementum/cmd/ii/job_do.go:108 +0x358
          github.com/spf13/cobra.(*Command).execute(0x105242880,
          {0x140007080f0, 0x1, 0x1})
          /Users/ajm/go/pkg/mod/github.com/spf13/cobra@v1.10.2/command.go:1015
          +0x7d4 github.com/spf13/cobra.(*Command).ExecuteC(0x105242b60)
          /Users/ajm/go/pkg/mod/github.com/spf13/cobra@v1.10.2/command.go:1148
          +0x350 github.com/spf13/cobra.(*Command).Execute(...)
          /Users/ajm/go/pkg/mod/github.com/spf13/cobra@v1.10.2/command.go:1071
          main.main() /Users/ajm/Work/incrementum/cmd/ii/main.go:16 +0xc8

          goroutine 16 [chan receive]: main.runJobDo.func2()
          /Users/ajm/Work/incrementum/cmd/ii/job_do.go:87 +0x6c created by
          main.runJobDo in goroutine 1
          /Users/ajm/Work/incrementum/cmd/ii/job_do.go:84 +0x284